# Generated by Django 3.0.4 on 2020-03-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200311_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='material',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='methods',
            new_name='instructions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(db_column='material', max_length=4000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(db_column='methods', max_length=4000),
        ),
    ]
