# Generated by Django 3.0.4 on 2020-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200329_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
