# Generated by Django 3.0.4 on 2020-04-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donate_time',
            field=models.DateTimeField(null=True),
        ),
    ]
